"""
render.py — regenerate conductor/STATUS.md from the SQLite DB (conductor/db.py).

Shape mirrors the old hand-written STATUS.md closely enough to stay readable:
  # LANE STATUS banner
  > open items grouped by area (was: the "PICK UP HERE NEXT SESSION" blockquote)
  reverse-chronological dated log_entries sections (title + body_md as-is)

Does not try to reproduce every historical nuance of the old file — just the shape.
"""
from __future__ import annotations

import datetime as _dt
from pathlib import Path

from db import get_connection

REPO_ROOT = Path(__file__).resolve().parent.parent
STATUS_PATH = REPO_ROOT / "conductor" / "STATUS.md"
EXPORT_PATH = REPO_ROOT / "conductor" / "status_export.md"


def _fetch_open_items(conn):
    return conn.execute(
        "SELECT * FROM items WHERE status NOT IN ('done', 'parked') ORDER BY area, "
        "CASE status WHEN 'blocked' THEN 0 ELSE 1 END, opened_date"
    ).fetchall()


def _fetch_parked(conn):
    return conn.execute(
        "SELECT * FROM items WHERE status = 'parked' ORDER BY area, id"
    ).fetchall()


def _fetch_pending_decisions(conn):
    return conn.execute(
        "SELECT * FROM decisions WHERE status = 'pending' ORDER BY id"
    ).fetchall()


def _fetch_log_entries(conn):
    return conn.execute(
        "SELECT * FROM log_entries ORDER BY date DESC, id DESC"
    ).fetchall()


def _group_by_area(items):
    grouped: dict[str, list] = {}
    for it in items:
        grouped.setdefault(it["area"] or "unclassified", []).append(it)
    return grouped


def build_markdown() -> str:
    conn = get_connection()
    try:
        open_items = _fetch_open_items(conn)
        parked_items = _fetch_parked(conn)
        pending_decisions = _fetch_pending_decisions(conn)
        log_entries = _fetch_log_entries(conn)
    finally:
        conn.close()

    today = _dt.date.today().isoformat()
    lines = []
    lines.append(f"# LANE STATUS  (generated by conductor/render.py, {today})")
    lines.append("")
    lines.append(
        "> Live dashboard, generated from `C:\\TradingDesk-Local\\conductor\\conductor.db`. "
        "Do not hand-edit this file — run `conductor/cli.py log/open/close` then "
        "`conductor/cli.py render`. RAW SESSION HANDOFFS live in `conductor/handoffs/` + "
        "dated `docs/SESSION_HANDOFF_*.md`."
    )
    lines.append(">")

    if open_items:
        grouped = _group_by_area(open_items)
        lines.append("> **OPEN ITEMS, by area:**")
        for area in sorted(grouped):
            lines.append(f">")
            lines.append(f"> **{area}**")
            for it in grouped[area]:
                tag = " [BLOCKED]" if it["status"] == "blocked" else ""
                notes = f" — {it['notes']}" if it["notes"] else ""
                lines.append(f"> - (#{it['id']}){tag} {it['title']}{notes}")
    else:
        lines.append("> **No open items.**")

    if pending_decisions:
        lines.append(">")
        lines.append("> **PENDING DECISIONS:**")
        for d in pending_decisions:
            opts = f" | options: {d['options']}" if d["options"] else ""
            lines.append(f"> - (#{d['id']}) [{d['lane']}] {d['question']}{opts}")

    if parked_items:
        lines.append(">")
        lines.append(f"> **PARKED / SHELVED ({len(parked_items)})** — off the active list, restore with `conductor/cli.py unpark --id N`:")
        for it in parked_items:
            lines.append(f"> - (#{it['id']}) [{it['area']}] {it['title']}")

    lines.append("")

    for entry in log_entries:
        tag = f" ({entry['session_tag']})" if entry["session_tag"] else ""
        lines.append(f"### {entry['date']}{tag} — {entry['title']}")
        if entry["body_md"]:
            lines.append(entry["body_md"])
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render() -> str:
    """Regenerate conductor/STATUS.md and conductor/status_export.md. Returns the text."""
    text = build_markdown()
    STATUS_PATH.write_text(text, encoding="utf-8")
    EXPORT_PATH.write_text(text, encoding="utf-8")
    return text


if __name__ == "__main__":
    out = render()
    print(f"Rendered {STATUS_PATH} and {EXPORT_PATH} ({len(out)} chars)")
