"""
version.py — single source of truth for the paperbot system version + change log.

Compliance/traceability: every run STAMPS this version (plus the config knobs and the
per-account model as_of) into its report header and — once order routing exists — into
each audit-ledger record, so any trade decision can be tied back to the exact logic and
settings that produced it. Bump VERSION whenever behavior that can change an order
changes, and add a CHANGELOG line saying WHAT changed and WHY.

This is the lightweight in-code marker. It is NOT a substitute for source-control
history (git) — it complements it. The CHANGELOG here is the human-readable summary;
the repo (when initialized) is the authoritative line-by-line record.
"""
from __future__ import annotations

# 0.MAJOR.MINOR while pre-trading. Bump on ANY change that can affect a generated order
# (strategy wiring, sizing, reserve/band logic, allocation, routing).
VERSION = "0.25.1"

# Newest first. Keep terse; for an examiner the "why" matters as much as the "what".
CHANGELOG = [
    ("0.25.1", "2026-07-29", "s0_live_deploy: removed the --model-clear affirmation gate and "
                             "IBKR model-overlay detection — model divestment is handled "
                             "manually by the account owner (explicit direction; the check was "
                             "unwanted friction). All other deploy safety gates unchanged "
                             "(single-account wall U14438624, --arm-i-understand + --conform "
                             "both required, live gateway read-only arming probe, two-phase "
                             "cash-gate, straggler re-price, per-run ref, <=50% NetLiq per-order "
                             "cap, total-buy<=investable, buying-power check, kill switch, "
                             "in-process READONLY/DRY_RUN flip in try/finally, preview-by-"
                             "default). Rule #1 clean: no strategy/regime/band/sizing value "
                             "touched. NOTHING transmitted editing or testing it (fully mocked)."),
    ("0.25.0", "2026-07-28", "s0_live_deploy REBUILT SAFER after the 2026-07-28 first live "
                             "deploy went ~$40k NEGATIVE (conductor #63 / log #145). Four "
                             "order-affecting fixes: (1) TWO-PHASE CASH-GATED execution — "
                             "phase 1 transmits ONLY the sells (plan sells + conform ALIEN "
                             "liquidations) and WAITS for terminal state; between phases it "
                             "RE-READS live TotalCashValue (realized cash, never the plan's "
                             "expected proceeds); phase 2 sizes buys to that ACTUAL cash with "
                             "a hard invariant (total BUY notional <= cash*(1-1% buffer)), "
                             "whole-share scaling/skipping buys if a sell fell short — buying "
                             "against money that hasn't arrived is now structurally impossible "
                             "(root cause: BUCK's ~$40k sell cancelled, so $115k of buys "
                             "committed against ~$76k). (2) STRAGGLER RE-PRICE — an unfilled "
                             "leg is cancelled + re-placed at a more aggressive marketable "
                             "limit toward the far touch, up to 3 attempts, re-placing only "
                             "the unfilled remainder; a leg still unfilled at the cap is left "
                             "cancelled and reported LOUDLY, never silently dropped. (3) "
                             "PER-RUN order ref — the deploy ref now carries a per-run stamp "
                             "so a fresh run's legs never match a prior run's fills (fixes the "
                             "re-fire false-block where a bought-then-sold SPY looked 'already "
                             "done'); correctness comes from the engine's delta-vs-positions, "
                             "and double-submit protection is kept by a symbol+side check "
                             "against currently WORKING open orders (ref-independent). (4) "
                             "MODEL PRE-CHECK — a new REQUIRED --model-clear human affirmation "
                             "gate (the account was still in IBKR model 'Main', invisible to "
                             "our sub-account read-only lane); armed deploy hard-stops without "
                             "it, plus a best-effort master-level detection that refuses on a "
                             "positively-detected non-empty modelCode. All prior gates intact "
                             "(arm token, conform, kill switch, single-account U14438624 wall, "
                             "<=50% NetLiq per-order cap, total-buy<=investable, price guard, "
                             "gateway-armed probe, in-process READONLY/DRY_RUN flip in "
                             "try/finally, preview-by-default). Rule #1 clean: no strategy/"
                             "regime/band/sizing value touched — execution-safety only. "
                             "NOTHING transmitted building or testing it (fully mocked). "
                             "+two-phase/re-price/per-run-ref/model-gate test matrix."),
    ("0.24.1", "2026-07-28", "s0_live_deploy: give deploy orders their own :deploy ref "
                             "namespace so the dedup gate no longer false-blocks on a "
                             "collision with the one-off tiny-test (or normal rebalances); "
                             "re-send protection unchanged."),
    ("0.24.0", "2026-07-28", "add s0_live_deploy.py -- full-account DEPLOY executor with "
                             "explicit --conform mode (liquidates non-S0 holdings to deploy "
                             "any book into the S0 GROWTH-tier target); armed+conform gated, "
                             "whole-share, price-guarded, dedup, notional-capped (total BUY "
                             "<= investable; no single order > 50% NetLiq), sells-before-buys, "
                             "pinned to U14438624."),
    ("0.23.0", "2026-07-28", "s0_live_exec retargeted to trust account U14438624 "
                             "(Andrew-authorized; U5721712 PDT-blocked); single-account wall "
                             "repointed, all other caps unchanged."),
    ("0.22.0", "2026-07-27", "S0 tiny-test REAL-TRANSMISSION path (Andrew-authorized): new "
                             "s0_live_exec.py — the desk's FIRST order path that can transmit a "
                             "real order, on the funded individual live TEST account U5721712 on "
                             "the Live-Trade Gateway (port 4003; NEVER the trust account "
                             "U14438624). It reuses the read-only pilot verbatim for WHAT to trade "
                             "(strategy_target.current_target -> rebalance_engine.plan_account "
                             "against U5721712 with live prices, filtered to the individual "
                             "account) and adds ONE capped, marketable LIMIT built with "
                             "order_router.build_marketable_limit and placed with "
                             "order_router.place(armed=True) — both UNCHANGED. PREVIEW BY DEFAULT: "
                             "with no flag it sizes, picks + builds the candidate, prints 'WOULD "
                             "TRANSMIT', and sends nothing. Transmission requires ALL of: the exact "
                             "--arm-i-understand token (sets armed=True; never defaulted), no "
                             "kill-switch sentinel (AUTOTRADE_DISABLED), target account EXACTLY "
                             "U5721712, a BUY of a whitelisted symbol (USFR only), qty <= "
                             "MAX_TEST_SHARES (1) AND shares*limit <= MAX_TEST_NOTIONAL ($150), 1 "
                             "order/run, the Gateway physically armed (Read-Only API toggle off, "
                             "measured live via arming's zero-transmission cancel-a-fabricated-"
                             "order probe mirrored against the open 4003 connection — arming.py "
                             "itself is paper-4002-only and can't be pointed at 4003 without "
                             "editing it), and the pre-transmit dedup gate "
                             "(order_router.already_present) FRESH. Miss any -> preview, prints "
                             "WHY. NEVER a market order. No auto-arm, nothing scheduled; a human "
                             "arms + fires. New connect_s0_live_armed() in s0_live.py (readonly="
                             "False, clientId s0_live_exec=58) is the ONLY armed lane; the "
                             "read-only pilot lane is untouched. Order-affecting (introduces real "
                             "transmission). Rule #1 clean: reuses strategy_target / "
                             "rebalance_engine / order_router / arming idiom / config UNCHANGED — "
                             "no strategy/regime/band/sizing value touched. NOTHING was transmitted "
                             "building or testing it (built + tested preview-only, fully mocked). "
                             "+offline test matrix (test_s0_live_exec.py)."),
    ("0.21.0", "2026-07-27", "S0 live-pilot PREVIEW path (conductor #3/#41, Slice 2): new "
                             "s0_live_pilot_run.py — the single-account analog of the paper FA "
                             "morning pipeline, pointed at a REAL funded account. It reads the "
                             "individual live-trading TEST account U5721712 on the Live-Trade "
                             "gateway (port 4003 — the same gateway S8 pilots on; S8 uses the "
                             "TRUST account U14438624 under the same login, never this one) via "
                             "the read-only s0_live lane (connect_s0_live -> "
                             "ibkr_live_trade.connect(readonly=True); readonly=False is never "
                             "passed), filters every read to U5721712 (never the trust account), "
                             "computes S0's target with the shared brain (strategy_target."
                             "current_target -> backtester run_backtest), fetches real-time "
                             "reference prices on 4003, sizes the target against the real account "
                             "with the UNCHANGED rebalance_engine.plan_account (config."
                             "REBALANCE_BAND_PCT band; reserve 0 since U5721712 is not in "
                             "cashflows.SCHEDULE), and prints + emails 'WOULD HAVE TRANSMITTED' "
                             "via the shared dailyreport mailer/status. ZERO-TRANSMIT with two "
                             "independent walls: (1) the connection is read-only, and (2) the "
                             "runner is BUILD/PREVIEW-ONLY — there is NO arm path and NO transmit "
                             "code in the file at all (imports no order_router; never calls "
                             "place()/place_laddered()/ib.placeOrder()/arming). MANUAL, on-demand "
                             "for now — deliberately NOT scheduled; the first pilot cycles are "
                             "human-reviewed before any automation. Order-affecting (new order-"
                             "sizing preview path against a real account), though it transmits "
                             "nothing. Rule #1 clean: reuses strategy_target / rebalance_engine / "
                             "reconcile / cashflows / config UNCHANGED — no strategy/regime/band/"
                             "sizing value touched. +offline test matrix "
                             "(test_s0_live_pilot_run.py)."),
    ("0.20.0", "2026-07-24", "Per-run margin/buying-power monitoring (conductor #26). New "
                             "margin_monitor.py snapshots accountSummary immediately before "
                             "and after the ARMED transmit in order_router.place()/"
                             "place_laddered(), diffs BuyingPower/ExcessLiquidity/"
                             "InitMarginReq/MaintMarginReq/AvailableFunds, and writes a "
                             "durable kind='margin_impact' record to the audit ledger "
                             "(runs.jsonl) for after-the-fact intraday margin review — "
                             "closing the gap where s4_risk.margin_preflight()'s result was "
                             "only printed, never persisted. Capture is per-RUN not "
                             "per-single-order (a per-leg accountSummary round-trip would add "
                             "latency and race fills) and fully fail-soft: any summary read "
                             "error degrades to margin=None and never blocks or alters order "
                             "transmission. nav_history.py daily CSV now also carries "
                             "buying_power + excess_liquidity columns (read from "
                             "accountValues the S0 monitor already pulls — no extra broker "
                             "call; pre-existing rows backfilled NaN) for an EOD margin time "
                             "series. Order-path-adjacent OBSERVABILITY only — no routing/"
                             "sizing/allocation/frozen-config change; S0 is cash-only so "
                             "nothing fires there today, this is the prerequisite for S8 "
                             "options going live in paperbot."),
    ("0.19.0", "2026-07-24", "flatten_accounts.py SAFETY REWORK (conductor #51 — was "
                             "HIGH-severity DO-NOT-RUN). The one-shot liquidation tool was "
                             "load-bearing-unsafe: it hardcoded all five DU sub-accounts, "
                             "took no args, hardcoded order.transmit=True, and RUNNING THE "
                             "MODULE WAS THE SWEEP — so a launch would liquidate the entire "
                             "live S0 book. It also priced EVERY position via a Stock() "
                             "quote, so an OPTION position was priced at the UNDERLYING and "
                             "legged out NAKED. Reworked: (a) argparse with REQUIRED "
                             "--accounts AND --symbols/--conids allowlists (no default) + a "
                             "hard guard at the top of main() that exits non-zero and never "
                             "connects if either is absent; --execute is now the ONLY thing "
                             "that transmits, DRY-RUN is the default (prints intended "
                             "orders, places nothing). (b) instrument-aware: refuses any "
                             "non-STK secType (OPT/FUT/BAG/…) with a loud warning and marks "
                             "the run non-flat — never prices off the underlying, never "
                             "legs out an option (combo-close left as an explicit TODO). "
                             "(c) flatten now validates its OWN limit price (rejects NaN / "
                             "non-finite / <=0 via math.isfinite — the old `if not ref:` let "
                             "NaN through) instead of trusting live_quotes upstream. (d) "
                             "cancels any still-working order before disconnect, and a "
                             "non-flat reconcile is now a HARD FAILURE (non-zero exit), not "
                             "a printed note. (e) copies the live position's contract before "
                             "forcing exchange=SMART instead of mutating it in place. "
                             "Order-affecting: changes which accounts/instruments the "
                             "liquidation tool will act on and how it routes/cancels — a "
                             "flatten can no longer default to 'everything in five "
                             "accounts' or send a mispriced naked option order. PAPER only; "
                             "+13-case offline test matrix (test_flatten_accounts.py). Rule "
                             "#1 clean: no strategy/regime/band/sizing value touched."),
    ("0.18.0", "2026-07-20", "S0 live-account reconciliation / corp-action guard (armed-live "
                             "prereq #3). reconcile.reconcile() gains an opt-in `universe` "
                             "param (the strategy's tradeable symbols, from a new "
                             "strategy.universe() accessor on StrategyBase/AdaptiveAllWeather "
                             "== set(strategies.config.ALL_TICKERS), verified a superset of "
                             "every sleeve's output) that SPLITS the single UNTRACKED status "
                             "into ROTATE_OUT (held, weight 0, symbol IN universe, int(sh)>=1 "
                             "-> a known ticker the model dropped -> SELL, normal rebalancing), "
                             "ALIEN (symbol NOT in universe / whitelist / cash -> corp-action "
                             "or manual holding -> REVIEW, never auto-traded), FRACTIONAL "
                             "(int(sh)==0, sh!=0 -> DRIP stub, suppressed from the band so it "
                             "stops false-paging nightly), and SWEEP (whitelisted cash/MMF). "
                             "`universe is None` (backtester + every existing caller) "
                             "reproduces today's UNTRACKED classification bit-for-bit. "
                             "rebalance_engine.band_breached now breaches on ROTATE_OUT (and "
                             "genuine trade-size drift) but NEVER on ALIEN/FRACTIONAL/SWEEP; "
                             "plan_account emits a sell delta for ROTATE_OUT, NOTHING for "
                             "ALIEN/FRACTIONAL/SWEEP, and collects ALIEN lines onto "
                             "AccountPlan.alien_lines. universe threaded through "
                             "plan_accounts/build_plan. New config.SWEEP_WHITELIST (default "
                             "EMPTY, discover-then-whitelist) extends the investable.CASH_SYMBOL "
                             "anchor. nightly_monitor_run + morning_execute_run emit a distinct "
                             "CORP-ACTION / UNTRACKED REVIEW alert on any ALIEN holding without "
                             "blocking legitimate ROTATE_OUT/DRIFTED/MISSING rebalancing (an "
                             "alien-only cycle is 'needs review', not a false 'band breach, no "
                             "routes' page). recon_report shows the new statuses + a quiet "
                             "FRACTIONAL/SWEEP line + an ALIEN review section. Order-affecting: "
                             "changes which held symbols the engine will and won't auto-trade "
                             "(a spinoff/rename is no longer churned into a taxable round-trip; "
                             "a known dropped ticker still sells). Behavior-identical on paper/"
                             "backtester when no universe is passed; +live-reconciliation test "
                             "matrix. Rule #1 clean: no frozen strategy/regime/band/sizing value "
                             "changed (REBALANCE_BAND_PCT, cash_reserve_pct, ALL_TICKERS et al. "
                             "untouched) — this is reconciliation plumbing + a safety gate. "
                             "Still zero-transmit (PILOT_MODE/READONLY/DRY_RUN unchanged)."),
    ("0.17.0", "2026-07-20", "S0 order idempotency: the deterministic orderRef is now "
                             "ENFORCED, not just documented. New pre-transmit dedup gate "
                             "order_router.already_present() reads BROKER TRUTH "
                             "(reqAllOpenOrders working refs + reqExecutions today's fills "
                             "per orderRef; NEVER whatIfOrder) and a new append-only "
                             "transmit_journal.py (ATTEMPTING/SENT/CYCLE_COMPLETE JSONL "
                             "under STATE_DIR, off Drive) to classify each leg FRESH/"
                             "WORKING/COMPLETE/PARTIAL/UNKNOWN; only FRESH transmits, "
                             "everything else transmits nothing (PARTIAL/UNKNOWN also "
                             "alert). Fails CLOSED: any broker-read error -> UNKNOWN. Wired "
                             "per-leg at the top of the transmit branch of place() and "
                             "before rung 1 of place_laddered(). morning_execute_run path "
                             "[4] now journals ATTEMPTING before / SENT after each leg, "
                             "runs the gate in BOTH pilot (zero-transmit rehearsal, logs "
                             "WOULD SEND/WOULD SKIP) and armed modes, and calls "
                             "ledger.record_run() per cycle (closes the missing per-run "
                             "audit line). Staged-file archive is now a tidy-up, not the "
                             "safety mechanism. Order-affecting (routing/idempotency): a "
                             "crash-resume, retry, manual re-run, or stacked ladder no "
                             "longer double-sends what the broker already has working or "
                             "filled. Still zero-transmit today (PILOT_MODE/READONLY/"
                             "DRY_RUN unchanged); +order-idempotency test matrix."),
    ("0.16.0", "2026-07-17", "S8 live-pilot margin preflight fixed for the real "
                             "live-trade account (port 4003, U14438624). Two order-gating "
                             "corrections, both found by reading the live account: (1) the "
                             "login exposes TWO managed accounts (trust U14438624 + "
                             "individual U5721712) plus an 'All' aggregate, so s8_runner "
                             "now filters ib.accountSummary() to s8_config.ACCOUNT before "
                             "the preflight (new filter_account_summary; fail-closed refuse "
                             "if the target account is absent) -- previously _summary_map's "
                             "last-write-wins collapse let the preflight read the WRONG "
                             "account's numbers. (2) s4_risk.account_is_margin now also "
                             "treats BuyingPower > NetLiquidation as margin: IBKR reports "
                             "AccountType='TRUST'/'INDIVIDUAL' (legal-entity label, no "
                             "'MARGIN' token) for this account, which the string-only test "
                             "wrongly refused; BP>NLV is impossible on a cash account, a "
                             "definitive margin tell with no tunable threshold (rule #1 "
                             "clean). s8_risk passes BuyingPower/NetLiquidation into the "
                             "check; S4's own call stays string-only (unchanged). "
                             "Order-affecting: fixes whether an S8 spread entry is approved "
                             "by the margin gate. Still zero-transmit (PILOT_MODE=True, "
                             "connect readonly=True, gateway ReadOnlyApi=yes); +6 tests."),
    ("0.15.0", "2026-07-09", "DU8922144 and DU8922146 removed from ENROLLMENT "
                             "(Andrew's explicit decision, freeing them up for testing "
                             "other strategies later, e.g. S4/S8). Balanced and Growth "
                             "tiers go from 2-account FA blocks to single-account "
                             "enrollments; rebalance_engine.route_blocks() derives "
                             "routing from live account count per tier, so both tiers "
                             "now route DIRECT automatically (same mechanism that "
                             "already made Conservative/DU8922142 DIRECT) -- no routing "
                             "logic changed, just the ENROLLMENT map. Existing S0 "
                             "positions in the two freed accounts are to be liquidated "
                             "to cash separately, via a deliberate armed PAPER session "
                             "-- NOT part of this change. conductor/ACCOUNT_ALLOCATION.md "
                             "is now the authoritative account->strategy map (update it "
                             "alongside any future ENROLLMENT edit). Order-affecting: "
                             "changes which accounts S0 rebalances and how the two "
                             "affected tiers route."),
    ("0.14.0", "2026-07-09", "Automated nightly-monitor + morning-execute PILOT for "
                             "S0 (Andrew-approved, deliberate exception to the normally "
                             "sacred manual review->arm->transmit gate, discussed and "
                             "scoped in advance): nightly_monitor_run.py (~9:15 PM CT, "
                             "after EodReport) does one bounded-retry (3 attempts / "
                             "~10 min cap, always try/finally-disconnected) gateway "
                             "touch that folds in the old AccountMonitorDaily drift/"
                             "cashflow check, computes S0's current per-tier target, "
                             "and -- only if some enrolled account's plan needs "
                             "rebalancing (rebalance_engine's own band-breach test) AND "
                             "the new rebalance_guard.py passes (ticker allow-list "
                             "against strategies.config.ALL_TICKERS, a named "
                             "MAX_SINGLE_ACCOUNT_TURNOVER_PCT_NAV=0.50 notional cap per "
                             "account, and a regime cross-check against the exact "
                             "market_health_score()/apply_hysteresis() call eod_report's "
                             "9PM email uses) -- STAGES the route list as JSON under "
                             "C:\\TradingDesk-Local\\pending_trades\\YYYY-MM-DD.json. A "
                             "guard failure alerts by email and stages nothing. "
                             "morning_execute_run.py (~8:50 AM CT) makes ZERO gateway "
                             "contact on the common no-staged-file day; otherwise "
                             "checks a kill-switch sentinel "
                             "(C:\\TradingDesk-Local\\AUTOTRADE_DISABLED), re-runs the "
                             "guard defensively against fresh prices/regime (never "
                             "trusts the staged file blindly), and -- because "
                             "PILOT_MODE=True (the hardcoded default; only Andrew may "
                             "flip it to False after reviewing pilot cycles) -- logs and "
                             "emails 'WOULD HAVE TRANSMITTED: ...' instead of calling "
                             "any order-placing code, then archives the staged file. "
                             "The PILOT_MODE=False path (not exercised by this release) "
                             "reuses rebalance_execute.py's own arm/build/place/ladder "
                             "functions verbatim rather than reimplementing them. New "
                             "clientIds 46 (paperbot_nightly_monitor) / 47 "
                             "(paperbot_morning_execute). Existing manual "
                             "rebalance_run.py / rebalance_execute.py CLIs are "
                             "untouched and remain the human-driven path. Two new "
                             "scheduled tasks (nightly monitor retimed onto the "
                             "AccountMonitorDaily slot at 9:15 PM CT; a new "
                             "MorningExecuteDaily task at 8:50 AM CT). Order-affecting: "
                             "introduces a real, if pilot-gated, path to unattended "
                             "paper trade staging; actual transmission remains fully "
                             "gated off by PILOT_MODE=True until a deliberate future "
                             "flip."),
    ("0.13.1", "2026-07-09", "Fixed NaN-as-bearish bug in S0 regime scoring: a "
                             "missing daily price (Tiingo hasn't published yet) "
                             "previously read as a false bearish trend/vol/duration "
                             "break via bare pandas `>` comparisons (NaN>NaN/NaN>0 "
                             "== False, not NaN) instead of unknown/hold-prior-"
                             "state, and pct_change's legacy pad-fill silently "
                             "turned a missing print into a fake flat 0% return. "
                             "Fixed in 4 places: regime.py's trend component "
                             "(_ratio_above_trend, _trend_component's "
                             "trend_above_10m/trend_ret_6m_pos, and the SPY-"
                             "realized-vol stress fallback), regime.py's "
                             "_rolling_slope_positive boolean cast (the docstring's "
                             "NaN-safety promise was undone by the final `> 0` "
                             "cast), volatility.py's realized_vol (was silently "
                             "reading a data-gap night as falsely calm, nudging "
                             "toward MORE equity exposure), and duration.py's "
                             "_above_ma (feeds the live Duration Filter's long-"
                             "Treasury permission/ban rules; now NaN-aware with an "
                             "explicit conservative .fillna(False) at each call "
                             "site, matching gates.is_above's existing convention "
                             "for permission gates). Also fixed eod_report.py: "
                             "'Data as-of' now reports the OLDEST last-real-value "
                             "date across S0's required inputs instead of the "
                             "newest date ANY ticker reached (was able to read "
                             "'fresh' on a night a required ticker's row was NaN), "
                             "and s0_regime's status now inherits s0_data's status "
                             "when it's worse (ok<stale<warn<fail) so the two "
                             "sections can no longer disagree with s0_regime "
                             "looking healthier. Order-affecting: changes S0's "
                             "regime/duration computation on any date with a "
                             "missing input price. Byte-identical when all inputs "
                             "are present (pure NaN-handling fix); backtester + "
                             "paperbot both pick this up automatically via the "
                             "shared strategies package, no separate paperbot "
                             "change needed."),
    ("0.13.0", "2026-07-04", "S4 (SPX vol-control fund) single-account daily REVIEW path, "
                             "shelf-ready. New S4-only siblings (frozen S0 paths untouched): "
                             "s4_strategy_target (shared-brain adapter -> Target, profile "
                             "runtime dial + stale-data guard), s4_sizing (REAL-margin "
                             "leverage sizing: SPY notional = NAV*exposure, exposure may "
                             "exceed 1.0x, borrow leg carried NOT dropped), s4_risk (guard "
                             "permits up to the profile leverage_cap + fail-closed margin "
                             "preflight refusing the >1.0 path on a cash/insufficient-BP "
                             "account), s4_rebalance_run (single-account, gateway-locked, "
                             "place(armed=False)), s4_daily_run (calendar-gated entry point). "
                             "clientIds 44 (paperbot_s4) + 45 (paperbot_s4_exec, reserved). "
                             "Order-affecting: introduces the levered S4 sizing/risk path. "
                             "Transmits nothing; no scheduled task registered; not armed."),
    ("0.12.0", "2026-06-30", "Rebalance run/execute acquire the gateway lock for the whole "
                             "session and wait-then-refuse (naming the holder) if it's held; "
                             "monitor skips on busy. Single-process gateway interlock now "
                             "active (clientIds + lock)."),
    ("0.11.0", "2026-06-30", "Withdrawal earmark fence + sale-raised nudge in monitor core; "
                             "live read-only monitor shell (account_monitor_run.py, clientId "
                             "40) reads SettledCashByDate/fills, persists baselines, runs "
                             "decide(), prints propose-only verdicts. No scheduler yet (held)."),
    ("0.10.0", "2026-06-30", "Deposit-detection core (pure): SettledCashByDate baseline + "
                             "executions cross-check distinguishes external deposit from "
                             "sale-raised/dividend; over-trading guards + per-day debounce; "
                             "emits propose-only DEPOSIT_ARRIVED. No broker connection / no "
                             "scheduler yet (Slice 6b)."),
    ("0.9.0", "2026-06-30", "Per-account monitor brain (account_monitor.py): pure "
                            "Verdict/decide() core — HOLD/REBALANCE/ALERT, propose-only, "
                            "transmits nothing. Withdrawal-coverage + drift + "
                            "untracked-position verdicts; deposit detection deferred to "
                            "Slice 6. Real client schedule data not included (SCHEDULE "
                            "stays empty)."),
    ("0.8.0", "2026-06-30", "Explicit execution-side CASH bucket (~1.5%); risk lines "
                            "reconcile against true model weights; phantom drift removed. "
                            "Backtester untouched; order sizing unchanged."),
    ("0.7.0", "2026-06-30", "Cash buffer 5%->1.5% via single config knob "
                            "(cash_reserve_pct=0.015); risk positions now size ~3.5% of "
                            "NAV closer to model. Order-affecting."),
    ("0.6.0", "2026-06-30", "Consolidated the investable/buffer math into a single leaf "
                            "module investable.py (compute_investable + buffer_pct). The "
                            "5 sites that re-derived (NetLiq-reserve)*(1-cash_reserve) "
                            "inline — rebalance_engine, reconcile, recon_report, "
                            "execution_engine, and the risk_manager reserve threshold — "
                            "now share that one function (rebalance_engine.compute_investable "
                            "kept as a thin re-export). Buffer stays 0.05; proven "
                            "behavior-identical (full paperbot suite green, +8 "
                            "characterization tests pinning the math at 0.05). Slice 1 of "
                            "the account-cashflow build: consolidation only, NO behavior "
                            "change."),
    ("0.5.0", "2026-06-27", "Pure offline multi-account block REBALANCE ENGINE "
                            "(rebalance_engine.py): per-account reserve carve-out + "
                            "explicit integer target shares + per-holding no-trade band; "
                            "same-tier/symbol/side block aggregation with per-account "
                            "ContractsOrShares split (sums to block qty); single-account "
                            "true-up falls back to a DIRECT order. Emits order_router "
                            "inputs as a transmit-free RoutePlan with fa_method='' (the "
                            "group's ContractsOrShares governs; faMethod='NetLiq' is "
                            "rejected, Err 10226). 14 pytest unit tests, all green. No "
                            "broker contact, no order object built, nothing transmitted."),
    ("0.4.0", "2026-06-26", "FA block-order plumbing: read-only FA-config probe "
                            "(fa_probe.py), order_router.build_fa_block(), and a "
                            "what-if-only block validator (fa_block_test.py). No "
                            "transmission, no config writes."),
    ("0.3.0", "2026-06-26", "Multi-account reconciliation + drift report; distribution "
                            "reserve (cashflows); no-trade band; block aggregation with "
                            "per-account allocation split. Read-only."),
    ("0.2.0", "2026-06-26", "Multi-account discovery (accounts.py) + per-tier enrollment "
                            "map. Read-only."),
    ("0.1.0", "2026-06-26", "Single-account dry-run engine: target / diff / risk / build. "
                            "Read-only, transmits nothing."),
]


def banner() -> str:
    """One-line version marker for report headers and logs."""
    return f"paperbot v{VERSION}"


def stamp() -> dict:
    """Version fields to merge into an audit-ledger record (layer 2 of traceability)."""
    return {"paperbot_version": VERSION}
